config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static#home'
  resources :sessions, only: %i[new create destroy]
  namespace :moderator do
    resources :blog_posts do
      resources :approvals, only: %i[new create destroy]
      post 'decline', as: 'decline', action: :destroy, controller: "approvals"
      resources :suggestions, only: %i[new create]
    end
  end

  resources :blog_posts do
    resources :comments
    scope module: :blog_posts do
      resource :status_save, only: %i[create]
      resource :status_submit, only: %i[create]
    end
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
# frozen_string_literal: true

class BlogPost < ApplicationRecord
  enum status: %w[saved submitted approved declined published edit_requested]
  belongs_to :user
  has_many :comments
  has_many :suggestions
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :blog_posts
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :authenticate
  protect_from_forgery

  def authenticate
    render file: '/public/404.html' if current_user.nil?
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/blog_posts/status_saves_controller.rb
# frozen_string_literal: true

module BlogPosts
  class StatusSavesController < ApplicationController

    def create
      result = BlogPost::Operation::StatusSave.(params: params)
      if result
        flash[:notice] = "#{result[:model].title} has been saved."
        return redirect_to blog_post_path(result[:model].id)
      end
      flash[:alret] = "There was an error saving the post"
      redirect_to blog_post_path(result[:model].id)
    end
  end
end

app/controllers/blog_posts/status_submits_controller.rb
# frozen_string_literal: true

module BlogPosts
  class StatusSubmitsController < ApplicationController

    def create
      result = BlogPost::Operation::StatusSubmit.(params: params)
      if result
        flash[:notice] = "#{result[:model].title} has been submited."
        return redirect_to blog_post_path(result[:model].id)
      end
      flash[:alret] = "There was an error submiting the post"
      redirect_to blog_post_path(result[:model].id)
    end
  end
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true

class BlogPostsController < ApplicationController

  def index
    render :index, locals: { blog_posts: blog_posts }
  end

  def show
    render :show, locals: { blog_post: blog_post }
  end

  def new
    run BlogPost::Operation::Create::Present
    render :new, locals: { form: @form}
  end

  def create
    result = BlogPost::Operation::Create.(params: params, current_user: current_user)
    if result
      flash[:notice] = "#{result[:model].title} has been created"
      return redirect_to blog_post_path(result[:model].id)
    else
      flash[:alert] = "#{result["contract.default"].errors.messages}"
      redirect_back(fallback_location: new_blog_post_path)
    end
  end

  def edit
    run BlogPost::Operation::Update::Present
    render :edit, locals: { form: @form}
  end

  def update
    result = BlogPost::Operation::Update.(params: params, current_user: current_user)
    if result
      flash[:notice] = "#{result[:model].title} has been saved"
      return redirect_to blog_post_path(result[:model].id)
    else
      flash[:alert] = "#{result["contract.default"].errors.messages}"
      redirect_back(fallback_location: edit_blog_post_path(params[:id]))
    end
  end


  def destroy; end

  private

  def _run_options(options)
    options.merge( "current_user" => current_user )
  end

  def blog_posts
    @blog_posts ||= BlogPost.where(user_id: current_user.id)
  end

  def blog_post
    @blog_post ||= BlogPost.find(params[:id])
  end
end

app/controllers/moderator/approvals_controller.rb
# frozen_string_literal: true

module Moderator
  class ApprovalsController < ModeratorController



    def new
      render :new, locals: { blog_post: blog_post }
    end

    def create
      result = ::BlogPost::Moderator::Operation::Approve.call(params: params)
      if result[:approved]
        flash[:notice] = 'Post has been approved!'
      else
        flash[:alert] = result[:errors]
      end
      redirect_to moderator_blog_posts_path
    end

    def destroy
      result = ::BlogPost::Moderator::Operation::Decline.call(params: params)
      if result[:declined]
        flash[:notice] = 'Post has been declined!'
      else
        flash[:alert] = result[:errors]
      end
      redirect_to moderator_blog_posts_path
    end

    private

    def blog_post
      @blog_post ||= BlogPost.find(params[:blog_post_id])
    end
  end
end

app/controllers/moderator/blog_posts_controller.rb
module Moderator
  class BlogPostsController < ModeratorController
    def index
      render :index, locals: {posts: BlogPost.all}
    end
  end
end

app/controllers/moderator/comments_controller.rb
module Moderator
  class CommentsController < ModeratorController
  end
end

app/controllers/moderator/moderator_controller.rb
# frozen_string_literal: true

module Moderator
  class ModeratorController < ApplicationController
    before_action :authenticate_mod

    def authenticate_mod
      render file: '/public/404.html' if !session[:moderator]
    end
  end
end

app/controllers/moderator/suggestions_controller.rb
# frozen_string_literal: true

module Moderator
  class SuggestionsController < ModeratorController
    def new
      render :new, locals: { blog_post: blog_post }
    end

    def create
      result = ::BlogPost::Moderator::Operation::Suggest.call(params: params, current_user: current_user)
      if result
        flash[:notice] = 'Suggestions have been submitted!'
      else
        flash[:alert] = result[:errors]
      end
      redirect_to new_moderator_blog_post_approval_path(blog_post.id)
    end

    private

    def blog_post
      @blog_post ||= BlogPost.find(params[:blog_post_id])
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate
  def new
    render :new
  end

  def create
    result = Session::Operation::Authenticate.(params: params)
    if result[:authenticated] && result[:user].moderator?
      session[:user_id] = result[:user].id
      session[:moderator] = true
      flash[:notice] = 'You are now logged in!'
      redirect_to moderator_blog_posts_path
    elsif result[:authenticated]
      session[:user_id] = result[:user].id
      flash[:notice] = 'You are now logged in!'
      redirect_to root_path
    else
      flash[:alert] = result[:error]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:moderator] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  skip_before_action :authenticate
  def home
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.haml
.row
  .col-sm-9
    %h1 Edit
.row
  .col-sm-4
    = form_with model: @form do |f|
      %div.form-group
        = f.label :title
        = f.text_field :title,  class: "form-control", id: "title"
      %div.form-group
        = f.label :description
        = f.text_field :description,  class: "form-control", id: "description"
      %div.form-group
        = f.label :content
        = f.text_area :content, size: "60x12",  class: "form-control", id: "content"
      %div.form-group
        =submit_tag 'Submit', class: 'btn btn-primary mb-2'

app/views/blog_posts/index.haml
.container-fluid
  .row
    - blog_posts.each do |post|
      %div.post_preview
        .col-sm
          %h1
            %u
              =link_to "#{post.title}", blog_post_path(post.id), class: "text-primary stretched-link"
        .col-md-12
          %p
            = post.description
        .col-sm-6
          = fa_icon "comments", text: post.comments.size
        .col-sm-6
          -case post.status
          -when "submitted"
            Submitted
          -when "declined"
            Declinded
          -when "approved"
            Approved
          - when "saved"
            Saved
          -when "published"
            Published
          -when "edit_requested"
            Changes Requested

app/views/blog_posts/new.haml
.row
  .col-sm-9
    %h1 New Post
.row
  .col-sm-4
    = form_with model: @form do |f|
      %div.form-group
        = f.label :title
        = f.text_field :title, class: "form-control", id:"title"
      %div.form-group
        = f.label :description
        = f.text_field :description, class: "form-control", id:"description"
      %div.form-group
        = f.label :content
        = f.text_area :content, size: "60x12", class: "form-control", id:"content"
      %div.form-group
        =submit_tag 'Submit', class: 'btn btn-primary mb-2'

app/views/blog_posts/show.haml
.container-fluid
  .row
    .col-sm-3
      %h1
        = blog_post.title
    .col-sm-3
      = button_to "Edit", edit_blog_post_path(blog_post_id: blog_post.id), :class => "btn btn-info mb-2", method: :get
      = form_tag blog_post_status_save_path(blog_post_id: blog_post.id), method: :post do |form|
        =submit_tag 'Save', class: 'btn btn-warning mb-2', "data-toggle"=>"tooltip", "data-placement" => "top", title: "This will indicate that this post is not ready to be published"
      = form_tag blog_post_status_submit_path(blog_post_id: blog_post.id) do |form|
        =submit_tag 'Submit', class: 'btn btn-primary mb-2',"data-toggle"=>"tooltip", "data-placement" => "top", title: "This will indicate that this post is ready to be published"
  .row
    .col-md
      %h4
        Description:
      %h5{:style => "margin-left: 13px;"}
        = blog_post.description
      %h2
        Content:
      %h3{:style => "margin-left: 13px;"}
        = blog_post.content
      %h2
        Status:
      %h3{:style => "margin-left: 13px;"}
        = blog_post.status.capitalize
      %p
        = "Author: #{blog_post.user.email}"

app/views/blog_posts/status_saves/create.haml
%p
  some

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TbBlog
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = javascript_pack_tag 'side_bar'
    .wrapper
      - if session[:user_id]
        = render "shared/sidebar"
      %div#content
        -if notice
          .alert.alert-success{:role => "alert"}
            = notice
        -elsif alert
          .alert.alert-danger{:role => "alert"}
            = alert
        - if session[:user_id]
          = render "shared/nav_bar"
        = yield

app/views/moderator/approvals/new.haml
.container-fluid
  .row
    .col-sm-3
      %h1
        = blog_post.title
    .col-sm-3
      = form_tag moderator_blog_post_approvals_path, method: :post do |form|
        =submit_tag 'Approve', class: 'btn btn-primary mb-2'
      = form_tag moderator_blog_post_decline_path(blog_post_id: blog_post.id) do |form|
        =submit_tag 'Decline', class: 'btn btn-danger mb-2'
      = button_to "Add Suggestions", new_moderator_blog_post_suggestion_path(blog_post_id: blog_post.id), :class => "btn btn-info mb-2", method: :get
  .row
    .col-md
      %h4
        Description:
      %h5{:style => "margin-left: 13px;"}
        = blog_post.description
      %h2
        Content:
      %h3{:style => "margin-left: 13px;"}
        = blog_post.content
      %p
        = "Author: #{blog_post.user.email}"

app/views/moderator/blog_posts/index.haml
.container-fluid
  .row
    - posts.each do |post|
      %div.post_preview
        .col-sm
          %h1
            = post.title
        .col-md-12
          %p
            = post.description
          %p
            Author:
            = post.user&.email
        .col-sm-6
          = fa_icon "comments", text: post.comments.size
        .col-sm-6
          -case post.status
          -when "submitted"
            %u
              =link_to "Approve/Decline/Suggest", new_moderator_blog_post_approval_path(post.id), class: "text-primary stretched-link"
          -when "declined"
            Declinded
          -when "approved"
            Approved
          - when "saved"
            Saved
          -when "published"
            Published
          -when "edit_requested"
            Changes Requested

app/views/moderator/suggestions/new.haml
= form_tag moderator_blog_post_suggestions_path(blog_post_id: blog_post.id), method: :post do |form|
  %div.form-group
    %label{:for => :content} Suggestion
    %input.form-control{id: "suggestion", type: "text", placeholder: "Type your suggestion here", name: "content"}
  =submit_tag 'Submit', class: 'btn btn-primary mb-2'

app/views/shared/_nav_bar.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %button#sidebarCollapse.btn.btn-info{:type => "button"}
      = fa_icon "bars"
      %span Toggle Sidebar
      %span
      %span
      %span
    %h6{:style => "margin-left: 13px;"}
      ="Logged in as #{current_user.email}"
      %span{:style => "margin-left: 13px;"}
        %a.badge.badge-dark{:href => logout_path} Log Out
    %button.btn.btn-dark.d-inline-block.d-lg-none.ml-auto{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %svg.svg-inline--fa.fa-align-justify.fa-w-14{"aria-hidden" => "true", "data-fa-i2svg" => "", "data-icon" => "align-justify", "data-prefix" => "fas", :role => "img", :viewbox => "0 0 448 512", :xmlns => "http://www.w3.org/2000/svg"}
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.nav.navbar-nav.ml-auto
        %li.nav-item.active
          %a.nav-link{:href => root_path} Home
        %li.nav-item
          %a.nav-link{:href => blog_posts_path} Blog Posts
        - if session[:moderator]
          %li.nav-item
            %a.nav-link{:href => moderator_blog_posts_path} Blog Posts Approval
%br/

app/views/shared/_sidebar.haml
%nav#sidebar
  .sidebar-header
    %h3 Blog Sidebar
  %ul.list-unstyled.components
    %p Navigation
    %li.active
      %a.toggle{"aria-expanded" => "false", "data-toggle" => "collapse", :href => root_path} Home
    %li
      %a{:href => new_blog_post_path} Write a new post
    %li
      %a{:href => "#"} Contact